### PR TITLE
Add VisionFive 2

### PR DESCRIPTION
**Pull request by roberth**
This adds support for the next generation board.

As mentioned in the README, I'm not happy about the kernel, nor should anyone be, but I figured it's worth sharing, as it took a lot of effort and it's the best starting point at this time.

### CODE REVIEW

**Comment by MatthewCroughan** [comment]
This is fantastic. So good.

**Comment by MatthewCroughan** [comment]
It would be nice to have a `nix run .#flash /dev/mmcblk0p1` instead of the documentation that you have included, just going to merge and eventually get around to doing this.

**Comment by roberth** [comment]
> It would be nice to have a `nix run .#flash /dev/mmcblk0p1` instead of the documentation that you have included, just going to merge and eventually get around to doing this.

```diff
-mmcblk0p1
+mmcblk0
```

Would be nice to catch that mistake if someone makes it in real life.

A CLI tool that takes care of the unmounting and perhaps even device selection would be nice to reuse, but I couldn't find one.

**Comment by MatthewCroughan** [comment]
@roberth Sure, we'd effectively be making a bash wrapper around `dd`, `mount` and more and that is runnable via `nix`. I don't think it's a bad idea.

**Pull request merged**
